spring.application.name=vault-chat-app-backend

# spring.data.mongodb.uri=mongodb://localhost:27017/vaultchatapp
#spring.data.mongodb.uri=mongodb+srv://pattanaikbishwajit_db_user:jack264@cluster0.ub3gwas.mongodb.net/vaultdb?retryWrites=true&w=majority

spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT:8080}
